FROM python:3.9

ARG USERNAME
ARG PASSWORD
ARG CLUSTER_NAME
ARG DB_NAME
ARG TABLE_NAME
ARG URL
ARG PORT

ENV USERNAME $USERNAME
ENV PASSWORD $PASSWORD
ENV CLUSTER_NAME $CLUSTER_NAME
ENV DB_NAME $DB_NAME
ENV TABLE_NAME $TABLE_NAME
ENV URL $URL
ENV PORT $PORT

COPY main.py requirements.txt app/
WORKDIR /app
RUN pip install -r requirements.txt

EXPOSE $PORT
CMD python /app/main.py