name: Build and push to Dockerhub

on:
  push:
    branches:
      - 'jk-etl'

jobs:
  docker:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: actions/checkout@v3
        run: echo "${{ secrets.DOCKERHUB_USERNAME }}" 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./app
          file: ./Dockerfile
          push: true
          build-args: |
            "USERNAME=${{ secrets.USERNAME}}"
            "PASSWORD=${{ secrets.PASSWORD}}"
            "DB_NAME=${{ secrets.DB_NAME}}"
            "TABLE_NAME=${{ secrets.TABLE_NAME }}"
            "URL=${{ secrets.URL }}"
            "PORT=${{ secrets.PORT }}"
          tags: recipes/latest
