name: Publish DockerHub image

on:
  push:
    branches:
      - 'main'

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.IMG_NAME }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: |
            "USERNAME=${{ secrets.USERNAME}}"
            "PASSWORD=${{ secrets.PASSWORD}}"
            "CLUSTER_NAME=${{ secrets.CLUSTER_NAME}}"
            "DB_NAME=${{ secrets.DB_NAME}}"
            "TABLE_NAME=${{ secrets.TABLE_NAME }}"
            "URL=${{ secrets.URL }}"
            "PORT=${{ secrets.PORT }}"
          tags: ${{ steps.meta.outputs.tags }}
